apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: team-2
spec:
  interval: 10m0s
  serviceAccountName: team-2
  sourceRef:
    kind: GitRepository
    name: team-2
  path: ./apps
  prune: true
  validation: client